# Generated by Django 5.2.9 on 2025-12-03 03:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.IntegerField()),
                ('category_name', models.CharField(max_length=100)),
                ('is_positive', models.IntegerField()),
                ('image_metadata', models.TextField()),
                ('image_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GadResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.IntegerField()),
                ('question_2', models.IntegerField()),
                ('question_3', models.IntegerField()),
                ('question_4', models.IntegerField()),
                ('question_5', models.IntegerField()),
                ('question_6', models.IntegerField()),
                ('question_7', models.IntegerField()),
                ('difficulty', models.CharField(default='Not specified', max_length=50)),
                ('is_filled', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.IntegerField()),
                ('left_count', models.IntegerField()),
                ('right_count', models.IntegerField()),
                ('final_prediction', models.CharField(max_length=50)),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LLMResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_llm', models.TextField()),
                ('techniques', models.TextField()),
                ('next_steps', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prediction_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_responses', to='home.predictiondata')),
            ],
        ),
    ]
