# Generated by Django 5.2.9 on 2026-06-07 02:20

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
import pgvector.django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='SessionEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('llm_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.llmresponse')),
                ('prediction_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.predictiondata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
